name: Gateway-Prod

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 15.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Cache node_modules
          uses: actions/cache@v2
          with:
            path: |
              ~/node_modules
            key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

      - name: Run Build
        run: yarn run build

      - name: Run Test
        run: yarn run test:cov

      - name: Run e2e
        run: yarn run test:e2e

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: toxictoast/gateway-api:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
